CREATE TABLE `CATEGORIA` (
  `COD_CATE` CHAR(6) PRIMARY KEY,
  `NOMBRE` VARCHAR(30)
);

CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` CHAR(6) PRIMARY KEY,
  `DESCRIPCION` VARCHAR(100),
  `PRECIO_VENTA` DECIMAL,
  `STOCK_MINIMO` INTEGER,
  `STOCK_ACTUAL` INTEGER,
  `COD_CATE` CHAR(6),
  `COD_SEDE` CHAR(6)
);

CREATE TABLE `DIRECCION` (
  `ID_DIRECCION` CHAR(7) PRIMARY KEY,
  `NOMBRE_DISTRITO` VARCHAR(20),
  `DEPARTAMENTO` VARCHAR(20),
  `PROVINCIA` VARCHAR(20),
  `DET_DIRECCION` VARCHAR(100),
  `REFERENCIA` VARCHAR(100)
);

CREATE TABLE `SEDE` (
  `COD_SEDE` CHAR(6) PRIMARY KEY,
  `NOMBRE_SEDE` VARCHAR(20),
  `AFORO` INT,
  `NUM_PISOS` INT,
  `ID_DIRECCION` CHAR(7)
);

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` CHAR(8) PRIMARY KEY,
  `NOMBRES` VARCHAR(30),
  `APELLIDOS` VARCHAR(50),
  `TELF` CHAR(9),
  `EMAIL` VARCHAR(30)
);

CREATE TABLE `DIREC_CLIENTE` (
  `ID_DIRECCION` CHAR(7),
  `ID_CLIENTE` CHAR(8),
  `FECHA_ASOCIACION` DATETIME
);

CREATE TABLE `EMPLEADO` (
  `COD_EMPLE` CHAR(6) PRIMARY KEY,
  `NOMBRES` VARCHAR(30),
  `APELLIDOS` VARCHAR(50),
  `DNI_EMPLE` CHAR(8),
  `ESTADO_CIVIL` VARCHAR(15),
  `NIVEL_EDUCA` VARCHAR(20),
  `TELF` CHAR(9),
  `EMAIL` VARCHAR(30),
  `FECHA_INGRESO` DATETIME,
  `COD_CARGO` CHAR(6),
  `COD_SEDE` CHAR(6)
);

CREATE TABLE `CARGOS` (
  `COD_CARGO` CHAR(6) PRIMARY KEY,
  `NOMBRE_CARGO` VARCHAR(20),
  `SUELDO_BASICO` DECIMAL
);

CREATE TABLE `BOLETA` (
  `NUM_BOLETA` CHAR(10) PRIMARY KEY,
  `FECHA_EM` DATETIME,
  `ESTADO_BOLETA` VARCHAR(15),
  `TOTAL` DECIMAL,
  `ID_CLIENTE` CHAR(8),
  `COD_EMPLE` CHAR(6)
);

CREATE TABLE `DETALLEBOLETA` (
  `NUM_BOLETA` CHAR(10) PRIMARY KEY,
  `ID_PRODUCTO` CHAR(6),
  `CANTIDAD` INT,
  `IMPORTE` DECIMAL,
  `IGV` DECIMAL
);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_CATE`) REFERENCES `CATEGORIA` (`COD_CATE`);

ALTER TABLE `SEDE` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `DIREC_CLIENTE` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `DIREC_CLIENTE` ADD FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_CARGO`) REFERENCES `CARGOS` (`COD_CARGO`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`COD_EMPLE`) REFERENCES `EMPLEADO` (`COD_EMPLE`);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`NUM_BOLETA`) REFERENCES `BOLETA` (`NUM_BOLETA`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO` (`ID_PRODUCTO`);
